version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
    - .:/app
    ports:
      - "8000:8765"
    command: python manage.py runserver 0.0.0.0:8765
    depends_on:
      - db
      - redis
  db:
    image: postgres
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"