# Generated by Django 2.2.10 on 2020-02-08 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import protector.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='Type URL Address that you want to protect', verbose_name='URL Address')),
                ('file', models.FileField(blank=True, upload_to=protector.utils.get_resource_file_path, verbose_name='File')),
                ('protected_url', models.CharField(blank=True, max_length=120)),
                ('password', models.CharField(blank=True, max_length=15)),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Visits')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
            },
        ),
    ]
