# Generated by Django 2.2.10 on 2020-02-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL Address")),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="media/", verbose_name="File"
                    ),
                ),
            ],
        ),
    ]
