# Generated by Django 2.2.10 on 2020-02-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protector", "0002_auto_20200206_1014"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="protected_url",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
