# Generated by Django 2.2.10 on 2020-02-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protector", "0003_resource_protected_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="password",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
