# Generated by Django 2.2.10 on 2020-02-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protector", "0005_auto_20200207_1154"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="visits",
            field=models.PositiveIntegerField(default=0, verbose_name="Visits"),
        ),
    ]
