# Generated by Django 2.2.10 on 2020-02-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protector", "0006_resource_visits"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resource",
            options={"verbose_name": "Resource", "verbose_name_plural": "Resources"},
        ),
        migrations.AlterField(
            model_name="resource",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
